# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure_pipeline

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      buildName: 'linux_release'
    mac:
      imageName: 'macos-10.13'
      buildName: 'osx_release'
 #   windows:
#      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: |
    chmod -R 777 ./tools/travis/
    ./tools/travis/$(buildName)/before_install.sh
  displayName: 'before_install'
- script: ./tools/travis/$(buildName)/install.sh
  displayName: 'install'
- script: ./tools/travis/$(buildName)/before_script.sh
  displayName: 'before_script'
- script: ./tools/travis/$(buildName)/script.sh
  displayName: 'script'
- script: ./tools/travis/$(buildName)/after_success.sh
  displayName: 'after_success'