# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
 #   mac:
 #     imageName: 'macos-10.13'
 #   windows:
#      imageName: 'vs2017-win2016'

#pool:
 # vmImage: $(imageName)

jobs:
- job: before_install
  steps:
  - script: ./tools/travis/linux_release/before_install.sh

- job: install
  dependsOn: before_install
  steps:
  - script: ./tools/travis/linux_release/install.sh

- job: before_script
  dependsOn: install
  steps:
  - script: ./tools/travis/linux_release/before_script.sh

- job: script
  dependsOn: before_script
  steps:
  - script: ./tools/travis/linux_release/script.sh

- job: after_success
  dependsOn: script
  steps:
  - script: ./tools/travis/linux_release/after_success.sh