# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
  maxParallel: 3

steps:
- script:  . tools/travis/travis_release/before_install.sh
  displayName: 'before_install'

- script: . tools/travis/travis_release/install.sh
  displayName: 'install'

- script: . tools/travis/travis_release/before_script.sh
  displayName: 'before_script'

- script: . tools/travis/travis_release/script.sh
  displayName: 'script'

- script: . tools/travis/travis_release/after_success.sh
  displayName: 'after_success'
