# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure_pipeline

strategy:
  matrix:
    linux_release:
      imageName: 'ubuntu-16.04'
      buildName: 'linux_release'
#    linux_minimal: #Does not work yet since minimal version should work with Qt 5.1 which is not supported in a Azure hosted env.
#      imageName: 'ubuntu-16.04'
#      buildName: 'linux_minimal'
    linux_tests:
      imageName: 'ubuntu-16.04'
      buildName: 'linux_tests'
    documentation:
      imageName: 'ubuntu-16.04'
      buildName: 'documentation'
    coverity:
      imageName: 'ubuntu-16.04'
      buildName: 'coverity'
    osx_release:
      imageName: 'macos-10.13'
      buildName: 'osx_release'
#    windows_release:
#      imageName: 'vs2017-win2016'
#      buildName: 'windows_release'

pool:
  vmImage: $(imageName)

steps:
- script: |
    chmod -R 777 ./tools/travis/
    ./tools/travis/$(buildName)/before_install.sh
  displayName: 'before_install'
- script: ./tools/travis/$(buildName)/install.sh
  displayName: 'install'
- script: ./tools/travis/$(buildName)/before_script.sh
  displayName: 'before_script'
- script: ./tools/travis/$(buildName)/script.sh
  displayName: 'script'
- script: ./tools/travis/$(buildName)/after_success.sh
  displayName: 'after_success'